- name: create oai config directory
  file:
    path: /usr/local/etc/oai/freeDiameter
    state: directory

- name: get service route interface name
  shell: ip route | grep 10.0.7.0/24 | grep -oP '(?<=dev\s)\w+'
  register: SERVICE_INTERFACE

- name: set oai component interfaces
  set_fact:
    MME_INTERFACE: "{{SERVICE_INTERFACE.stdout}}"

- name: overwrite oai epc configs
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - { src: 'acl.j2', dest: '/usr/local/etc/oai/freeDiameter/acl.conf' }
    - { src: 'mme_fd.j2', dest: '/usr/local/etc/oai/freeDiameter/mme_fd.conf' }
    - { src: 'mme.j2', dest: '/usr/local/etc/oai/mme.conf' }